//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace todoist
{
    using System;
    using System.Collections.Generic;
    
    public partial class Комментарии
    {
        public int ID { get; set; }
        public string Текст { get; set; }
        public Nullable<int> ID_Задачи { get; set; }
        public Nullable<int> ID_Пользователя { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
    
        public virtual Задачи Задачи { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
